# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export SCREENDIR=$HOME/.screen

# bashrc_version 0.0.1

# golang环境相关
export GOPATH="$HOME/go"
export GO111MODULE=auto

# 其他
export GTAGSCONF=/usr/local/gtags/share/gtags/gtags.conf
export GTAGSLABEL=pygments
export SVN_EDITOR=vim

# 端口映射
function AddressPortMapping {
	# 需要映射的端口ID加在这里
	PORT_MAPPING=(
		# 80 # web
		2224 # ssh
		# 3306 # mysql
		# 6379 # redis
		# 8500 # consul
	)
	LINUX_IP=`ifconfig | grep "inet " | grep -v "127.0.0.1" | awk '{print $2}'`
	for CURR_PORT in ${PORT_MAPPING[@]}; do
		NEW_STRING="netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport="$CURR_PORT" connectaddress="$LINUX_IP" connectport="$CURR_PORT";"$NEW_STRING
	done

	# 此处的'pc'可在配置文件内替换为自己的windows地址，~/.ssh/config
	ssh pc $NEW_STRING > /dev/null
}

# 启动一键脚本
function RestartRun {
	screen -wipe > /dev/null
	AddressPortMapping > /dev/null
}

# 重启svn托管服务
function SVNAgent {
	pkill gpg-agent
	gpg-agent --daemon
}
